// Code generated by tygo. DO NOT EDIT.

//////////
// source: alliancestationstatus.go

export interface AllianceStationStatus {
  dsConnected: boolean;
  robotConnected: boolean;
}

//////////
// source: ipc_message.go

export interface IPCMessage {
  cmd: string;
  data: string;
}

//////////
// source: match.go

export interface Match {
  id: string;
  matchNumber: number /* int */;
  elimRound: number /* int */;
  elimGroup: number /* int */;
  elimInstance: number /* int */;
  type: 'qualification'|'elimination';
  red1: number /* int */;
  red2: number /* int */;
  red3: number /* int */;
  blue1: number /* int */;
  blue2: number /* int */;
  blue3: number /* int */;
}

//////////
// source: team.go

export interface Team {
  Id: number /* int */;
  Name: string;
  Nickname: string;
  City: string;
  StateProv: string;
  Country: string;
  RookieYear: number /* int */;
  RobotName: string;
  Accomplishments: string;
  WpaKey: string;
  HasConnected: boolean;
  FtaNotes: string;
}
