name: Format

on:
    push:
    pull_request:
        branches: ['main']

concurrency:
    group: format-${{ github.ref }}
    cancel-in-progress: true

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    format:
        name: 'Format Files'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install Packages
              run: bun install
            - name: Prettier
              run: bun run format
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'style: format files'
