name: Node

on:
    push:
    pull_request:
        branches: ['main']

jobs:
    backend:
        name: 'Build Backend'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.bun/install/cache
                      ./node_modules
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-bun
            - name: Install Packages
              run: bun install --frozen-lockfile
            - name: Check
              run: bun run backend:check
            - name: Build
              run: bun run backend:build
    frontend:
        name: 'Build Frontend'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.bun/install/cache
                      ./node_modules
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-bun
            - name: Install Packages
              run: bun install --frozen-lockfile
            - name: Check
              run: bun run frontend:check
            - name: Build
              run: bun run frontend:build
